CREATE TABLE album
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    album_id VARCHAR(64)                             NOT NULL,
    club_id  BIGINT                                  NOT NULL,
    name     VARCHAR(64)                             NOT NULL,
    CONSTRAINT pk_album PRIMARY KEY (id)
);

CREATE TABLE album_image_tokens
(
    album_id        BIGINT NOT NULL,
    image_tokens_id BIGINT NOT NULL,
    CONSTRAINT pk_album_imagetokens PRIMARY KEY (album_id, image_tokens_id)
);

ALTER TABLE album
    ADD CONSTRAINT uc_album_albumid UNIQUE (album_id);

ALTER TABLE album
    ADD CONSTRAINT FK_ALBUM_ON_CLUB FOREIGN KEY (club_id) REFERENCES club (id);

ALTER TABLE album_image_tokens
    ADD CONSTRAINT fk_albimatok_on_album FOREIGN KEY (album_id) REFERENCES album (id);

ALTER TABLE album_image_tokens
    ADD CONSTRAINT fk_albimatok_on_image_token FOREIGN KEY (image_tokens_id) REFERENCES image_token (id);

ALTER TABLE address
DROP
COLUMN address_id;

ALTER TABLE address
    ADD address_id VARCHAR(64) NOT NULL;

ALTER TABLE address
    ADD CONSTRAINT uc_address_addressid UNIQUE (address_id);

ALTER TABLE announcement
DROP
COLUMN announcement_id;

ALTER TABLE announcement
    ADD announcement_id VARCHAR(64) NOT NULL;

ALTER TABLE announcement
    ADD CONSTRAINT uc_announcement_announcement UNIQUE (announcement_id);

ALTER TABLE image_token
DROP
COLUMN image_token_id;

ALTER TABLE image_token
    ADD image_token_id VARCHAR(64) NOT NULL;

ALTER TABLE image_token
    ADD CONSTRAINT uc_image_token_imagetokenid UNIQUE (image_token_id);

ALTER TABLE users
DROP
COLUMN user_id;

ALTER TABLE users
    ADD user_id VARCHAR(64) NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT uc_users_userid UNIQUE (user_id);