ALTER TABLE team_post
    DROP CONSTRAINT FK_TEAM_POST_ON_CLUBUSER;

ALTER TABLE team_post
    ADD CONSTRAINT FK_TEAM_POST_ON_CLUBUSER FOREIGN KEY (club_user_id) REFERENCES club_user (id) ON DELETE SET NULL;

ALTER TABLE team_post_comment
    DROP CONSTRAINT FK_TEAM_POST_COMMENT_ON_CLUBUSER;

ALTER TABLE team_post_comment
    ADD CONSTRAINT FK_TEAM_POST_COMMENT_ON_CLUBUSER FOREIGN KEY (club_user_id) REFERENCES club_user (id) ON DELETE SET NULL;
