CREATE TABLE training_event
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_time TIMESTAMP WITHOUT TIME ZONE,
    duration  BIGINT,
    notes     TEXT,
    team_id   BIGINT,
    CONSTRAINT pk_training_event PRIMARY KEY (id)
);

CREATE TABLE training_event_present_leaders
(
    training_event_id  BIGINT NOT NULL,
    present_leaders_id BIGINT NOT NULL,
    CONSTRAINT pk_training_event_present_leaders PRIMARY KEY (training_event_id, present_leaders_id)
);

CREATE TABLE training_event_present_members
(
    training_event_id  BIGINT NOT NULL,
    present_members_id BIGINT NOT NULL,
    CONSTRAINT pk_training_event_present_members PRIMARY KEY (training_event_id, present_members_id)
);

ALTER TABLE training_event
    ADD CONSTRAINT FK_TRAINING_EVENT_ON_TEAM FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE;

ALTER TABLE training_event_present_leaders
    ADD CONSTRAINT fk_present_leaders_on_club_user FOREIGN KEY (present_leaders_id) REFERENCES club_user (id) ON DELETE CASCADE;

ALTER TABLE training_event_present_leaders
    ADD CONSTRAINT fk_present_leaders_on_training_event FOREIGN KEY (training_event_id) REFERENCES training_event (id) ON DELETE CASCADE;

ALTER TABLE training_event_present_members
    ADD CONSTRAINT fk_present_members_on_club_user FOREIGN KEY (present_members_id) REFERENCES club_user (id) ON DELETE CASCADE;

ALTER TABLE training_event_present_members
    ADD CONSTRAINT fk_present_members_on_training_event FOREIGN KEY (training_event_id) REFERENCES training_event (id) ON DELETE CASCADE;

