CREATE TABLE announcement
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    announcement_id    VARCHAR(255)                            NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    body               TEXT                                    NOT NULL,
    author_id          BIGINT                                  NOT NULL,
    last_updated_by_id BIGINT                                  NOT NULL,
    club_id            BIGINT                                  NOT NULL,
    show_author        BOOLEAN,
    CONSTRAINT pk_announcement PRIMARY KEY (id)
);

ALTER TABLE announcement
    ADD CONSTRAINT uc_announcement_announcement UNIQUE (announcement_id);

ALTER TABLE announcement
    ADD CONSTRAINT FK_ANNOUNCEMENT_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES club_user (id);

ALTER TABLE announcement
    ADD CONSTRAINT FK_ANNOUNCEMENT_ON_CLUB FOREIGN KEY (club_id) REFERENCES club (id);

ALTER TABLE announcement
    ADD CONSTRAINT FK_ANNOUNCEMENT_ON_LASTUPDATEDBY FOREIGN KEY (last_updated_by_id) REFERENCES club_user (id);