version: '3'

services:
  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_DB=clubhousedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
#psql -h localhost -p 5400 -U postgres -d clubhousedb