token:
  secret: ${token.secret}
  expiration: 604800

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/clubhouse_dev'
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL

logging:
  level:
    root: info
    nu:
      borjessons:
        clubhouse: debug
    org:
      springframework:
        web: info
        security: warn
