token:
  secret: ${token.secret}
  expiration: 604800

logging:
  level:
    root: info
    nu:
      borjessons:
        clubhouse: debug
    org:
      springframework:
        web: info
        security: warn

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5400/clubhousedb'
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:db;DB_CLOSE_DELAY=-1'
    username: sa
    password: sa
  h2:
    console:
      enabled: true




    

